name: worflow for syntax validation
on:
  workflow_dispatch: # gives a button in github ui to run the workflow

jobs:
  terraform_init:
    name: Deploy Site
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: 1.7.5

      - name: Terraform Init
        id: init
        run: terraform init

        # Run a terraform fmt to check syntax
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

        # Run a terraform validate
      - name: Terraform Validate
        id: validate
    # Run even if formatting fails
        if: success() || failure()
        run: terraform validate -no-color



      
