name: worflow for creation of resources
on:
  workflow_dispatch: # gives a button in github ui to run the workflow
jobs:
   run_terraform_code: #name of the job
    runs-on: ubuntu-latest #specify the runnner
    steps:         
      - name: checkout repo # 
        uses: actions/checkout@v4
      - name: setup pyhton # 
        uses: actions/setup-python@v4
        with:
            python-version: 3.11
      - name: run pyhton # 
        run: python script.p

   job2: # name of the job
    runs-on: ubuntu-latest #specify the runnner
    needs: job1
    env:
        SUPER_SECRET: ${{ secrets.JOBANS_SECRET}}
    steps:      
      - name: run secret
        run: |
            echo "$SUPER_SECRET"
      
      - name: check runner # check runner version
        run:   echo "name of the runner is $(hostname)"
        shell: bash

   job3: #name of the job
    runs-on: ubuntu-latest #specify the runnner
    needs: job2
    if: ${{always()}}
    steps:      
      - name: run cmd
        run: |
            echo "hello github actions"
